# Generated by Django 3.2.7 on 2021-10-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='О нас')),
                ('image', models.ImageField(upload_to='static/assets/images', verbose_name='Картинка')),
                ('separator', models.ImageField(upload_to='static/assets/images', verbose_name='Разделитель')),
                ('subtitle1', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('subtitle2', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('subtitle3', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('subtitle4', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('text1', models.TextField(verbose_name='Описание')),
                ('text2', models.TextField(verbose_name='Описание')),
                ('text3', models.TextField(verbose_name='Описание')),
                ('text4', models.TextField(verbose_name='Описание')),
                ('icon1', models.CharField(max_length=30, verbose_name='Иконка')),
                ('icon2', models.CharField(max_length=30, verbose_name='Иконка')),
                ('icon3', models.CharField(max_length=30, verbose_name='Иконка')),
                ('icon4', models.CharField(max_length=30, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
